services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecole
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: esperance
      POSTGRES_PASSWORD: esperance
      POSTGRES_DB: esperance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  pgdata: